api = "0.10"

[buildpack]
  id = "acodeninja/playwright-python"
  version = "0.1.1"

[[buildpack.licenses]]
  type = "MIT"
  uri = "https://github.com/acodeninja/buildpacks/blob/main/LICENSE"

[[targets]]
  os = "linux"
[[targets.architectures]]
  name = "amd64"
[[targets.distros]]
  name = "ubuntu"

[[stacks]]
  id = "io.buildpacks.stacks.jammy"
