api = "0.8"

[buildpack]
    id = "acodeninja/python-security"
    name = "ACodeNinja Buildpack for Python Security"
    version = "2.0.1"
    homepage = "https://github.com/acodeninja/buildpacks/tree/main/python-security"

    [[buildpack.licenses]]
        type = "MIT"
        uri = "https://github.com/acodeninja/buildpacks/blob/main/LICENSE"

[[targets]]
    os = "linux"
    [[targets.distros]]
        name = "ubuntu"

[metadata]
    include-files = ["bin/detect", "bin/build", "buildpack.toml"]
    [[metadata.dependencies]]
        stacks = ["io.buildpacks.stacks.jammy"]
    [[metadata.dependencies]]
        stacks = ["io.buildpacks.stacks.bionic"]

[[stacks]]
    id = "*"
